name: Run Tests

on:
  push:
    branches:
      - develop
    paths:
      - '**.html'
      - '**.js'
      - '**.json'
      - '**.css'
      - '**/test.yml'
      - '!dist/engine/core/**'
  pull_request:
    branches:
      - develop
    paths:
      - '**.html'
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/engine/core/**'

jobs:
  cypress-run:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
	  - uses: actions/setup-node@v4
		with:
			node-version: 22
      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
          build: yarn run build
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
